Repository dfds/aws-backup-observability, pull requests merged in 2023-08, with the labels that each got.

#2 Pin packages versions and add github actions
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  .github/workflows/enforce-pr-labels.yaml
  .github/workflows/trivy.yaml
  .github/workflows/upload-to-s3.yaml
  .gitignore
  backup-reporter-lambda/requirements.txt
  renovate.json
  versions.tf
Labels: release:major

#5 Update renovate.json
  renovate.json
Labels: release:major

#7 Update Terraform aws to ~> 4.67.0
  versions.tf
Labels: release:minor

#10 Use tag prefix
  .github/workflows/auto-release.yaml
Labels: release:major

#6 Update dependency boto3 to v1.28.28
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#15 Add CODEOWNERS file
  .github/CODEOWNERS
  backup-reporter-lambda/requirements.txt
Labels: norelease

#8 Update Terraform aws to v5
  versions.tf
Labels: release:major

#17 Update dependency boto3 to v1.28.29
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#18 Update Terraform aws to ~> 5.13.0
  versions.tf
Labels: release:minor

#20 Update dependency boto3 to v1.28.30
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#19 Update dependency aws_lambda_powertools to v2.23.0
  backup-reporter-lambda/requirements.txt
Labels: release:minor

#21 Update dependency boto3 to v1.28.31
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#22 Fix backup report plan + fmt
  backup-report-plan.tf
  lambda-backup-reporter.tf
  s3-bucket-backup-reports.tf
  variables.tf
Labels: release:patch

#23 Update dependency boto3 to v1.28.32
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#24 Fix lambda
  backup-reporter-lambda/main.py
  providers.tf
  variables.tf
Labels: release:patch

#25 Update dependency boto3 to v1.28.33
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#26 Update dependency boto3 to v1.28.34
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#27 Update Terraform aws to ~> 5.14.0
  versions.tf
Labels: release:minor

#28 Update dependency aws_lambda_powertools to v2.23.1
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#29 Update dependency boto3 to v1.28.35
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#30 Update dependency boto3 to v1.28.36
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#31 Update dependency boto3 to v1.28.37
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#32 Add service linked role
  s3-bucket-backup-reports.tf
  versions.tf
Labels: release:minor

#33 Add assume_role support
  providers.tf
  variables.tf
Labels: release:minor

#34 Update dependency boto3 to v1.28.38
  backup-reporter-lambda/requirements.txt
Labels: release:patch

#35 Update dependency boto3 to v1.28.39
  backup-reporter-lambda/requirements.txt
Labels: release:patch
